export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM'
export const CART_VALIDATION_MESSAGE = "CART_VALIDATION_MESSAGE"

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"
export const CART_CALCULATE_PRICE = "CART_CALCULATE_PRICE"

export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"