# Generated by Django 3.2.12 on 2022-03-20 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('isPaid', models.BooleanField(default=False, verbose_name='Paid')),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('isDelivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('deliverd_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
