# Generated by Django 3.2.12 on 2022-03-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220320_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isPublished',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
