# Generated by Django 3.2.12 on 2022-04-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
