# Generated by Django 3.2.12 on 2022-04-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_quantity_orderitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
